# SANDBOX STATE VALUES
SANDBOX_READY_STATE = "Ready"
SANDBOX_ERROR_STATE = "Error"
SANDBOX_ENDED_STATE = "Ended"

JSON_RESULTS_FOLDER = "json-results"
LOGS_FOLDER = "logs"

TIMESTAMP_FORMATTING = "%d-%m-%y_%H%M%S"